### PR TITLE
Update uk.po

### PR DESCRIPTION
**Pull request by stenox**
several strings were translated and corrected

### CODE REVIEW

**Comment by prawnsalad** [comment]
Thanks! Would you like to be added to our translation manager (poeditor.com) so that any future additions can be updated? As future Kiwi versions become available you will get an email asking if you can spare a few minutes to make sure your language is complete.

https://poeditor.com/join/project/0b060db7c4c5d631ab5fe8a9f7a71226

**Comment by stenox** [comment]
Yes! Just registered there and joined the project by following provided link :)
I close this PR and will create new one on the development branch.
Thanks!

**Comment by prawnsalad** [comment]
Great. No need to create a new PR, all translations will be synced from poeditor.com in the next few days with your changes that you make.

**Comment by stenox** [comment]
Great. So will continue there :)

**Comment by stenox** [comment]
So, I've already transfered my translations to poeditor.com

**Comment by prawnsalad** [comment]
Looks like there are a few left over - https://poeditor.com/projects/po_edit?order=&filter=ut&id=7719&id_language=173&search=

**Comment by stenox** [comment]
Yes, but they were not included into this PR. I'll translate them later.

**Pull request closed without merging**
