### PR TITLE
Redesign of the relaxed theme

### PR DESCRIPTION
**Pull request by ptersilie**
Merged what I started in #666 into the recent version of the relaxed theme.

### CODE REVIEW

**Comment by ptersilie** [comment]
kiwi_tabs

**Comment by prawnsalad** [comment]
Finally got round to trying this out (sorry it took so long). Looks good, but a few things stands out that are missing:
* The tabs look odd when it wraps onto 2 lines or the settings window is opened
* When tabs are in list mode (change in the settings) the background colours are all mismatched

**Comment by ptersilie** [comment]
Ah yes. I only ever use the tab mode so I didn't notice. I'll try to fix the list mode and see what I can do about the Settings tab.

Does the index.html use different style classes for list and tabs mode? If not, can I alter the index.html to do so?

**Comment by prawnsalad** [comment]
If the list view is enabled a `.chanlist_treeview` class will be added to #kiwi. The different #kiwi classes can be found near the bottom of this page: https://kiwiirc.com/docs/theming

**Comment by ptersilie** [comment]
I had a go at the list view and the settings tab wrapping over 2 lines. Have a look and let me know what you think.

**Comment by prawnsalad** [comment]
I think there's a slight glitch.. Only does it when the selected tab is on the top row though.
image


Maybe there's some CSS missing or something?
image

**Comment by ptersilie** [comment]
Ah, my bad for not testing this with lots of open channels. But looking at your screenshots I feel like we have to give up on the tabs design. I still like it, but it won't work with lots of channels due to the wrap around. I'll try and redesign the channel buttons a bit so that wrapping doesn't look that awful.

**Comment by prawnsalad** [comment]
hey @ptersilie did you have any luck working on those tabs?

**Comment by prawnsalad** [comment]
Proposing that the tab styles revert back to the styles from https://github.com/prawnsalad/KiwiIRC/pull/666 if no other options come about.

**Comment by ptersilie** [comment]
Sorry. I will have a look at this again soon.

**Comment by prawnsalad** [comment]
PR moved to https://github.com/prawnsalad/KiwiIRC/pull/778

**Pull request closed without merging**
