### PR TITLE
Added a new theme

### PR DESCRIPTION
**Pull request by ptersilie**
A picture is worth a thousand words:

kiwitheme

### CODE REVIEW

**Comment by ptersilie** [comment]
Made some more changes:

kiwi2

**Comment by prawnsalad** [comment]
Incase you didn't get messages on IRC a while ago - are you able to update this theme to the latest development branch? I'm finding it difficult to merge them together since yours is based on a much older version of kiwi.

**Comment by ptersilie** [comment]
Okay, I merged in the development branch and also made the top bar a bit darker again since I remember you weren't to fond of it being so bright. ;)

**Comment by CoryChaplin** [comment]
I would move the timestamps to the right side, it's more of a complementary information than the priority to me. Having them on the far right makes the text much more readable IMHO.

**Comment by LouisKottmann** [comment]
+1 for the timestamps on the far right

**Comment by ptersilie** [comment]
I don't mind either way. The problem is, though, that time, username and messages are inside divs. So if I make the timestamp float right, we get weird behaviour with long messages (see image).

Timestamp on the right


Afaik the only solution to this would be to change the html to not use divs (instead maybe tds or spans).

**Comment by CoryChaplin** [comment]
I like it that way. Are the timestamps at the begining of lines in the text in the channel or something ?

**Comment by ptersilie** [comment]
@CoryChaplin I'm not sure what you mean.

**Comment by CoryChaplin** [comment]
The [14:53]

**Comment by ptersilie** [comment]
Ah, sorry. That's the history from my ZNC server. Everytime I log out and back in, it posts the the last XXX messages I missed.

**Comment by CoryChaplin** [comment]
OK. I like it like that.

**Comment by ptersilie** [comment]
Well the only thing that annoys me is that the message wraps around the time (as seen in the above screenshot).

**Comment by ptersilie** [comment]
Nevermind fixed it. I wasn't thinking. :)

**Comment by prawnsalad** [comment]
Is there a screenshot of the latest changes?

Also, the CSS is still missing a fair bit from the latest versions. The largest one that I can tell from a glance, is the .notification classes at the bottom of all the other themes

**Comment by ptersilie** [comment]
@prawnsalad Oh, sorry I haven't seen the changes in the style.css. I'll see what I can do.

**Comment by ptersilie** [comment]
Lastest screenshot:

kiwi3

**Comment by ptersilie** [comment]
Created new PR #701 where I applied all changes to a recent version of the relaxed theme.

**Pull request closed without merging**
