### PR TITLE
Change how we invoke server modules.

### PR DESCRIPTION
**Pull request by M2Ys4U**
Modules should now export a factory method that is called with the path to the server directory instead of just `require()`ing a hard-coded path to the Module module.

This is a breaking change for server modules.

### CODE REVIEW

**Comment by prawnsalad** [comment]
Re-looking over this, is there any reason why the exported function in a module takes the server path as an argument instead of just passing in an instance of kiwiModules? Seems odd why a module should have to worry about filenames in the core.

**Comment by M2Ys4U** [comment]
Yes; One of the modules `require()`s a second file within the `server` directory.

**Comment by prawnsalad** [comment]
Ah I see it now. How about `function (kiwiModule, server_dir)`? Would make almost all custom modules easier to develop while keeping the option for some of the more integrated modules.

**Comment by M2Ys4U** [comment]
Yeah, that would work!

**Comment by M2Ys4U** [comment]
@prawnsalad: Okay, I've made that change :)

**Comment by prawnsalad** [comment]
Could this please be retargeted for the v1.0 branch. Only minor changes should be needed before we start making large breaking changes.

**Comment by M2Ys4U** [comment]
Closing in favour of #794

**Pull request closed without merging**
