### PR TITLE
Adding Dockerfile for Docker based deployments.

### PR DESCRIPTION
**Pull request by jmervine**
Hello!

First, love the app, so thanks! 

I want to use this a Docker context and therefore Dockerized it. Please feel free to push this to `prawnsalad/kiwiirc` if you'd like and change all README.md references of `jmervine` to `prawnsalad`. Otherwise, I'll watch your repo and do my best to re-build and push when updates are pushed.

Cheers!
J

### CODE REVIEW

**Comment by holizz** [comment]
Does this Dockerfile still work? I just ran

    docker build -t kiwiirc .
    docker run -ti --rm -p 7778:7778 kiwiirc

And when I visit http://localhost:7778/ and press start (whichever server I use, whether I have SSL enabled or not) it just prints these errors:

    2015-03-24 02:02:31 - error: [Uncaught exception] TypeError: Cannot read property 'on' of undefined stack=TypeError: Cannot read property 'on' of undefined
        at getConnectionFamilyCb (/src/server/irc/connection.js:265:35)
        at resolve6Cb (/src/server/irc/connection.js:561:17)
        at Object.asyncCallback [as callback] (dns.js:81:16)
        at Object.onresolve [as oncomplete] (dns.js:201:10)

**Comment by jmervine** [comment]
I haven't tried it since submitting the PR, but did at the time. I'll mess with it later tonight or tomorrow and reply.

**Comment by prawnsalad** [comment]
There was a bug in the master branch that effected node 0.12 versions. The fixed has now been pushed into master so this docker file should be working  again now.

@jmervine: I don't think the Docker file belongs in this repo as it isn't required for the project. However if you add it into Dockers image registry I'll be happy to include it into the readme.

**Comment by jmervine** [comment]
I added it with the hope that you would setup auto build on the docket registry, building a new image every time you push changes.

**Comment by Xe** [comment]
+1

**Pull request closed without merging**
